In [5]:
import numpy as np  # linear algebra
import matplotlib.pyplot as plt  # plotting
import scipy.optimize  # gradient check

In [8]:
a = np.array([[5,8],[2,1],[6,7]])
b = np.array([[5,8,3],[2,1,9]])
result = a@b
print(result)

[[41 48 87]
 [12 17 15]
 [44 55 81]]


In [11]:
c = np.array([[1,2],[2,4]])
eigen = np.linalg.eig(c)
print(eigen[0])

[0. 5.]
